### ISSUE TITLE
BSpline output transform is not always correct

### ISSUE THREAD

**Issue by lassoan** [lassoan/SlicerElastix#33]
SlicerElastix can import linear and bspline transform from Elastix internal format, but sometimes the resulting transform is not accurate (gives different result than when a grid transform is generated).

How to reproduce: register MRHead volume to MRBrainTumor1 sample data set using default registration preset. Create output volume and output transform. The output volume matches the fixed volume very well, but applying the output transform to the moving volume results in much less accurate alignment.

Workaround: enable "Force grid output transform" in advanced section.

**Comment by erin5116** [comment]
I thought I was going crazy because the images (not the original moving image) I resampled using the resulting transform wasn't looking right..

In regards to the proposed workaround - how can we use the grid transform to resample images in Slicer? I was previously using the Resample Image (BRAINS) module to resample the images, but that module doesn't take grid trasnforms..the displacement field option is depreciated, and selecting the grid transform in the current "Transform file" input results in an error:
> Resample Image (BRAINS) standard error:
> 
> ERROR:  Invalid type (DisplacementFieldTransform) D:\D\S\Slicer-4102-build\BRAINSTools\BRAINSCommonLib\GenericTransformImage.cxx 399

Also, for me the bug seems to be the bspline transform. My result transform includes two transforms, one affine and one bspline. When I apply it to an image using the Resampling modeul, e.g. the original moving image, it appears that only the affine is applied and the bspline does not. 
Same happened when I used sitk in python, in case it was a Slicer thing. Seeing that the tfm file did contain bspline transform parameters, I tried to isolate it using sitk.CompositeTransforms, but when it was applied to an image it did nothing (like identity transform).

One last thing - can you confirm whether the Elastix internal format transformation.txt files should be the original/accurate format, and is there a way to read these files and save as another transformation format? I've been saving these files, so would be great to be able to recover transformations from them instead of computing it again from scratch.

**Comment by lassoan** [comment]
> In regards to the proposed workaround - how can we use the grid transform to resample images in Slicer?

There are several other image resampling modules in Slicer that can take an additional transform and you can also just apply and harden the transform on your volume.

> can you confirm whether the Elastix internal format transformation.txt files should be the original/accurate format

Yes.



> is there a way to read these files and save as another transformation format?

You can convert to a a displacement field (grid transform). Many of us asked Elastix developers to please use standard ITK file formats but they have other priorities. Deep learning/AI sucks resources away from everything else, so I don't think Elastix developers would have capacity to implement ITK transformation file support.

**Comment by lassoan** [comment]
Fixed in https://github.com/lassoan/SlicerElastix/commit/7e995863436927705802e32f50152d5246e90792
